services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mydb

  frontend:
    build:
      context: ./odoo-audits-frontend
      dockerfile: ../Dockerfile.frontend
    volumes:
      - ./odoo-audits-frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - backend
      
  frontend1:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend1
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4300:4200"
    depends_on:
      - backend
volumes:
  pgdata: